/* v2: GitHub Pages確認用。サービスワーカーは一旦使わず、キャッシュ問題を避けます。 */
const $ = (id) => document.getElementById(id);
function setStatus(msg, type="ok"){
  const el = $("statusBox");
  if(!el) return;
  el.textContent = "読込状態：" + msg;
  el.className = "status " + type;
}
window.addEventListener("error", e => setStatus("エラー: " + (e.message || e.type), "err"));
window.addEventListener("unhandledrejection", e => setStatus("処理エラー: " + (e.reason?.message || e.reason || "不明"), "err"));

if (window.pdfjsLib) {
  pdfjsLib.GlobalWorkerOptions.workerSrc = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
}

const state = {pdf:null,page:1,pages:0,canvasWidth:0,canvasHeight:0,scale:1,tx:0,ty:0,mode:"photo",selectedId:null,pendingId:null,records:[],dragging:false,lastX:0,lastY:0};
$("inspectionDate").value = new Date().toISOString().slice(0,10);
const padNo=n=>String(n).padStart(3,"0");
const safeName=s=>String(s||"橋梁").trim().replace(/[\\/:*?"<>|\s　]+/g,"_");
const extFromType=t=>!t?"jpg":t.includes("png")?"png":t.includes("webp")?"webp":(t.includes("heic")||t.includes("heif"))?"heic":"jpg";
const fileNameFor=rec=>`${safeName($("bridgeName").value)}_${padNo(rec.no)}.${rec.ext||"jpg"}`;
function getMeta(){return{bridgeName:$("bridgeName").value,routeName:$("routeName").value,inspectionDate:$("inspectionDate").value,inspector:$("inspector").value}}
function setMeta(m){if(!m)return;$("bridgeName").value=m.bridgeName||"";$("routeName").value=m.routeName||"";$("inspectionDate").value=m.inspectionDate||new Date().toISOString().slice(0,10);$("inspector").value=m.inspector||""}
async function renderPage(){if(!state.pdf)return;setStatus("PDF表示中", "ok");const page=await state.pdf.getPage(state.page);const v0=page.getViewport({scale:1});const viewer=$("viewer");const renderScale=Math.min(2.0,Math.max(900,viewer.clientWidth*1.6)/v0.width);const viewport=page.getViewport({scale:renderScale});const canvas=$("pdfCanvas");canvas.width=viewport.width;canvas.height=viewport.height;state.canvasWidth=viewport.width;state.canvasHeight=viewport.height;$("stage").style.width=viewport.width+"px";$("stage").style.height=viewport.height+"px";$("markerLayer").style.width=viewport.width+"px";$("markerLayer").style.height=viewport.height+"px";await page.render({canvasContext:canvas.getContext("2d"),viewport}).promise;$("emptyMessage").style.display="none";$("pageInfo").textContent=`${state.page} / ${state.pages}ページ`;fitView();renderMarkers();renderList();setStatus("PDF読込完了。写真モードで損傷位置をタップしてください。", "ok")}
function fitView(){const viewer=$("viewer");if(!state.canvasWidth||!state.canvasHeight)return;state.scale=Math.min(viewer.clientWidth/state.canvasWidth,viewer.clientHeight/state.canvasHeight)*0.98;state.tx=(viewer.clientWidth-state.canvasWidth*state.scale)/2;state.ty=12;applyTransform()}
function applyTransform(){$("stage").style.transform=`translate(${state.tx}px, ${state.ty}px) scale(${state.scale})`}
function clientToPdf(x,y){const r=$("viewer").getBoundingClientRect();return{x:(x-r.left-state.tx)/state.scale,y:(y-r.top-state.ty)/state.scale}}
function addRecordAt(p){if(!state.pdf){alert("先にPDF損傷図を読み込んでください。");return}const nextNo=state.records.length?Math.max(...state.records.map(r=>r.no))+1:1;const id=`rec_${Date.now()}_${Math.random().toString(16).slice(2)}`;const rec={id,no:nextNo,page:state.page,x:p.x/state.canvasWidth,y:p.y/state.canvasHeight,damageTitle:"",note:"",photoDataUrl:"",photoType:"image/jpeg",ext:"jpg",createdAt:new Date().toISOString()};state.records.push(rec);selectRecord(id);state.pendingId=id;renderMarkers();renderList();saveLocal();$("cameraInput").value="";$("cameraInput").click()}
function selectRecord(id){state.selectedId=id;const rec=state.records.find(r=>r.id===id);if(!rec){$("selectedInfo").textContent="未選択";$("damageTitle").value="";$("note").value="";$("photoPreview").innerHTML="";return}$("selectedInfo").textContent=`選択中：写真番号 ${padNo(rec.no)} ／ ${rec.page}ページ ／ ファイル名 ${fileNameFor(rec)}`;$("damageTitle").value=rec.damageTitle||"";$("note").value=rec.note||"";$("photoPreview").innerHTML=rec.photoDataUrl?`<img src="${rec.photoDataUrl}" alt="${padNo(rec.no)}">`:`<span class="hint">写真未添付</span>`;renderMarkers()}
function renderMarkers(){const layer=$("markerLayer");layer.innerHTML="";state.records.filter(r=>r.page===state.page).forEach(rec=>{const d=document.createElement("div");d.className="marker"+(rec.id===state.selectedId?" selected":"")+(rec.photoDataUrl?" hasPhoto":"");d.textContent=padNo(rec.no);d.style.left=(rec.x*state.canvasWidth)+"px";d.style.top=(rec.y*state.canvasHeight)+"px";d.addEventListener("pointerdown",e=>{e.stopPropagation();selectRecord(rec.id)});layer.appendChild(d)})}
function renderList(){const list=$("recordList");if(!state.records.length){list.innerHTML=`<p class="hint">まだ記録がありません。</p>`;return}list.innerHTML=state.records.slice().sort((a,b)=>a.no-b.no).map(rec=>`<div class="record" data-id="${rec.id}"><strong>${padNo(rec.no)}　${rec.damageTitle||"（損傷名未入力）"}</strong><div>ページ：${rec.page}</div><div>写真名：${fileNameFor(rec)}</div><div>備考：${rec.note||""}</div>${rec.photoDataUrl?`<img src="${rec.photoDataUrl}" alt="${padNo(rec.no)}">`:`<div class="hint">写真未添付</div>`}</div>`).join("");list.querySelectorAll(".record").forEach(el=>el.addEventListener("click",()=>selectRecord(el.dataset.id)))}
function updateRecord(){const rec=state.records.find(r=>r.id===state.selectedId);if(!rec){alert("記録を選択してください。");return}rec.damageTitle=$("damageTitle").value;rec.note=$("note").value;saveLocal();selectRecord(rec.id);renderList()}
function deleteRecord(){const rec=state.records.find(r=>r.id===state.selectedId);if(!rec)return alert("記録を選択してください。");if(!confirm(`${padNo(rec.no)} を削除しますか？`))return;state.records=state.records.filter(r=>r.id!==rec.id);state.records.sort((a,b)=>a.no-b.no).forEach((r,i)=>r.no=i+1);state.selectedId=null;saveLocal();selectRecord(null);renderMarkers();renderList()}
function fileToDataUrl(file){return new Promise((res,rej)=>{const reader=new FileReader();reader.onload=()=>res(reader.result);reader.onerror=rej;reader.readAsDataURL(file)})}
async function handlePhoto(file){if(!file)return;const rec=state.records.find(r=>r.id===(state.pendingId||state.selectedId));if(!rec){alert("写真を紐付ける記録がありません。");return}rec.photoDataUrl=await fileToDataUrl(file);rec.photoType=file.type||"image/jpeg";rec.ext=extFromType(rec.photoType);state.pendingId=null;saveLocal();selectRecord(rec.id);renderMarkers();renderList();setStatus(`${padNo(rec.no)} に写真を紐付けました`, "ok")}
function csvEscape(v){const s=String(v??"");return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function makeCsv(){const m=getMeta();const rows=[["橋梁名","路線名","点検日","点検者","写真番号","ページ","位置X","位置Y","写真ファイル名","損傷名・部材名","備考","作成日時"]];state.records.slice().sort((a,b)=>a.no-b.no).forEach(rec=>rows.push([m.bridgeName,m.routeName,m.inspectionDate,m.inspector,padNo(rec.no),rec.page,rec.x.toFixed(6),rec.y.toFixed(6),fileNameFor(rec),rec.damageTitle||"",rec.note||"",rec.createdAt||""]));return "\ufeff"+rows.map(r=>r.map(csvEscape).join(",")).join("\r\n")}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportCsv(){if(!state.records.length)return alert("記録がありません。");downloadBlob(new Blob([makeCsv()],{type:"text/csv;charset=utf-8"}),`${safeName($("bridgeName").value)}_写真一覧.csv`)}
function dataUrlToBlob(dataUrl){const[head,body]=dataUrl.split(",");const mime=(head.match(/data:(.*?);base64/)||[])[1]||"application/octet-stream";const bin=atob(body);const arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type:mime})}
async function exportZip(){if(!state.records.length)return alert("記録がありません。");if(!window.JSZip)return alert("JSZipが読み込めません。社内ネットワークでCDNがブロックされている可能性があります。");const zip=new JSZip();zip.file("写真一覧.csv",makeCsv());const pf=zip.folder("photos");state.records.slice().sort((a,b)=>a.no-b.no).forEach(rec=>{if(rec.photoDataUrl)pf.file(fileNameFor(rec),dataUrlToBlob(rec.photoDataUrl))});const blob=await zip.generateAsync({type:"blob"});downloadBlob(blob,`${safeName($("bridgeName").value)}_写真野帳.zip`)}
function saveLocal(){try{localStorage.setItem("bridgeInspectionPhotoAppV2",JSON.stringify({meta:getMeta(),records:state.records}))}catch(e){setStatus("一時保存容量を超えました。CSV/ZIP出力を優先してください。", "warn")}}
function loadLocal(){const raw=localStorage.getItem("bridgeInspectionPhotoAppV2");if(!raw)return alert("保存データがありません。");const d=JSON.parse(raw);setMeta(d.meta);state.records=d.records||[];state.selectedId=null;renderMarkers();renderList();selectRecord(null);alert("保存データを復元しました。PDFは再度読み込んでください。")}
function clearAll(){if(!confirm("全記録を削除しますか？"))return;state.records=[];state.selectedId=null;state.pendingId=null;localStorage.removeItem("bridgeInspectionPhotoAppV2");renderMarkers();renderList();selectRecord(null)}
$("pdfInput").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;if(!window.pdfjsLib){setStatus("PDF.jsが読み込めません。CDNブロックまたはネット接続を確認してください。", "err");return}try{setStatus("PDF読込中", "ok");const buf=await file.arrayBuffer();state.pdf=await pdfjsLib.getDocument({data:buf}).promise;state.pages=state.pdf.numPages;state.page=1;await renderPage()}catch(err){setStatus("PDF読込エラー: "+(err.message||err), "err")}});
$("btnPrev").addEventListener("click",async()=>{if(state.pdf&&state.page>1){state.page--;await renderPage()}});$("btnNext").addEventListener("click",async()=>{if(state.pdf&&state.page<state.pages){state.page++;await renderPage()}});$("btnFit").addEventListener("click",fitView);$("btnPhotoMode").addEventListener("click",()=>{state.mode="photo";$("btnPhotoMode").classList.add("primary");$("btnMoveMode").classList.remove("primary")});$("btnMoveMode").addEventListener("click",()=>{state.mode="move";$("btnMoveMode").classList.add("primary");$("btnPhotoMode").classList.remove("primary")});$("btnUpdateRecord").addEventListener("click",updateRecord);$("btnDeleteRecord").addEventListener("click",deleteRecord);$("btnRetake").addEventListener("click",()=>{if(!state.selectedId)return alert("記録を選択してください。");state.pendingId=state.selectedId;$("cameraInput").value="";$("cameraInput").click()});$("cameraInput").addEventListener("change",e=>handlePhoto(e.target.files[0]));$("btnExportCsv").addEventListener("click",exportCsv);$("btnExportZip").addEventListener("click",exportZip);$("btnSaveLocal").addEventListener("click",()=>{saveLocal();alert("一時保存しました。作業後はZIP出力してください。")});$("btnLoadLocal").addEventListener("click",loadLocal);$("btnClear").addEventListener("click",clearAll);["bridgeName","routeName","inspectionDate","inspector"].forEach(id=>$(id).addEventListener("change",saveLocal));
const viewer=$("viewer");viewer.addEventListener("pointerdown",e=>{if(e.target.classList.contains("marker"))return;viewer.setPointerCapture(e.pointerId);if(state.mode==="photo"){const p=clientToPdf(e.clientX,e.clientY);if(p.x<0||p.y<0||p.x>state.canvasWidth||p.y>state.canvasHeight)return;addRecordAt(p)}else{state.dragging=true;state.lastX=e.clientX;state.lastY=e.clientY}});viewer.addEventListener("pointermove",e=>{if(!state.dragging||state.mode!=="move")return;state.tx+=e.clientX-state.lastX;state.ty+=e.clientY-state.lastY;state.lastX=e.clientX;state.lastY=e.clientY;applyTransform()});viewer.addEventListener("pointerup",()=>state.dragging=false);viewer.addEventListener("pointercancel",()=>state.dragging=false);viewer.addEventListener("wheel",e=>{if(!state.pdf)return;e.preventDefault();const factor=e.deltaY<0?1.08:0.92;const before=clientToPdf(e.clientX,e.clientY);state.scale=Math.min(6,Math.max(0.15,state.scale*factor));const r=viewer.getBoundingClientRect();state.tx=e.clientX-r.left-before.x*state.scale;state.ty=e.clientY-r.top-before.y*state.scale;applyTransform()},{passive:false});
renderList();
setStatus(window.pdfjsLib && window.JSZip ? "アプリ読込完了。PDFを開いてください。" : "CDNライブラリ未読込。社内ネットワークでブロックされている可能性があります。", window.pdfjsLib && window.JSZip ? "ok" : "err");
